Add support for vagrant
I've been switching around platforms lately, so this will be helpful.

I had started trying this with Hyper-V, don't bother, Hyper-V is shit
with Vagrant, because:
- Pitiful selection of base boxes (Ubuntu Precise lol, still on this now)
- vswitches fuck everything up
  - Lost connectivity on the *host* repeatedly
  - No support for private+NAT
  - Vagrant doesn't seem to support many config changes
  - The guest tries to use IPv6 and just hangs doing nothing. This might
    just be my problem, who knows.
- Vagrant doesn't actually kill disk files on destroy
- Shell needs to run as admin to make it go
- Microsoft killed my pappy

Hyper-V seems pretty cool in isolation, nicer than VBox, but the bad
integration ruins it with Vagrant.

node 0.12 seems to work fine, but 4.x requires some newfangled version
of g++, so won't run on precise. I need to figure out my target
platform (i.e. lowest common demoninator between whatever feral and
whatbox and friends use) and primarily build against that.

Had to tweak ssl cert generation because I did it a bit wrong.

Apparently my deps are really out of date, I guess that's what happens
in node-land when you leave the room for 6 months. Should get on that.

diff --git a/config/ssl_setup b/config/ssl_setup
--- a/config/ssl_setup
+++ b/config/ssl_setup
@@ -4,11 +4,7 @@ BASEDIR=$(dirname $0)
 cd "$BASEDIR"
 
 # check openssl existence
-if ! which openssl &> /dev/null; then
-	which openssl
-	echo 'ERROR: openssl not found in PATH (see above)'
-	exit 1
-fi
+command -v openssl >/dev/null 2>&1 || { echo >&2 "ERROR: openssl not found"; exit 1; }
 
 cat <<EOF > tmpconfig
 [ req ]
